services:
  prometheus:
    image: prom/prometheus:v3.5.3
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus # Hãy dùng volume prom_data và gắn vào /prometheus.

  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  demo-app:
    build: ./app
    container_name: demo-app
    ports:
      - "8001:8000"
    restart: unless-stopped

volumes:
  prom_data: #Tạo/ quản lý một Docker volume tên là prom_data. 
