[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[OUTPUT]
    Name         loki
    Match        app.demo-app
    Host         loki
    Port         3100
    Labels       job=fluent-bit,service=demo-app,stream=$source
    Remove_Keys  container_id,container_name,source
    Line_Format  json
    Drop_Single_Key raw

[OUTPUT]
    Name         loki
    Match        app.inventory-service
    Host         loki
    Port         3100
    Labels       job=fluent-bit,service=inventory-service,stream=$source
    Remove_Keys  container_id,container_name,source
    Line_Format  json
    Drop_Single_Key raw
