services:
  demo-app:
    build:
      context: ./app
    container_name: demo-app
    ports:
      - "8001:8000"
    environment:
      OTEL_SERVICE_NAME: demo-fastapi-app
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=local,service.version=1.0.0
      OTEL_PYTHON_FASTAPI_EXCLUDED_URLS: metrics,health
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "app.demo-app"
        fluentd-async: "true"
        fluentd-sub-second-precision: "true"
    networks:
      - observability

  inventory-service:
    build:
      context: ./inventory
    container_name: inventory-service
    ports:
      - "8002:8000"
    environment:
      OTEL_SERVICE_NAME: inventory-service
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=local,service.version=1.0.0
      OTEL_PYTHON_FASTAPI_EXCLUDED_URLS: metrics,health
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "app.inventory-service"
        fluentd-async: "true"
        fluentd-sub-second-precision: "true"
    networks:
      - observability

networks:
  observability:
    name: observability_lab
    external: true
